version: 0.1

environment_variables:
  plaintext:
    DEBUG: "true"
            
phases:
  install:
    commands:
      - echo Install started on `date`
      - sudo apt-get update -y
      - sudo apt-get install -y wget gdebi-core git
      - wget https://packages.chef.io/files/stable/chefdk/1.3.40/ubuntu/16.04/chefdk_1.3.40-1_amd64.deb
      - sudo gdebi -n chefdk_1.3.40-1_amd64.deb
  pre_build: 
    commands:
      - echo ===========RUNNING TESTS ===========
  build:
    commands:
      - echo ===========RUNNNING BUILD ==========
      - foodcritic .
      - echo $?
      - rubocop -D
      - echo $?
  post_build:
    commands:
      - echo ===========RUNNING DEPLOY ==========
